# Generated by Django 4.2.1 on 2023-06-19 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idContacto', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de contact')),
                ('NombreContacto', models.CharField(max_length=30, null=True, verbose_name='Nombre del contacto')),
                ('correoContacto', models.EmailField(max_length=30, null=True, verbose_name='Correo del contacto')),
                ('TelefonoContacto', models.IntegerField(null=True, verbose_name='Telefono de contacto')),
                ('nombreMascota', models.CharField(max_length=30, null=True, verbose_name='Nombre de la mascota')),
                ('mensajeContacto', models.CharField(max_length=50, null=True, verbose_name='Mensaje del contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('codigoRaza', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la Raza')),
                ('nombreRaza', models.CharField(max_length=20, null=True, verbose_name='Nombre de la mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('idRespuestas', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Repsuesta')),
                ('contenidoRespuesta', models.CharField(max_length=50, null=True, verbose_name='Contendio de la respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de los servicios')),
                ('nombreServicio', models.CharField(max_length=35, null=True, verbose_name='Nombre de los servicios')),
                ('precioServicio', models.IntegerField(null=True, verbose_name='El precio de los servicios ')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de usuario')),
                ('nombrecompletoUsuario', models.CharField(max_length=50, null=True, verbose_name='Nombre del usuario')),
                ('correoUsuario', models.EmailField(max_length=45, null=True, verbose_name='Correo del usuario')),
                ('claveUsuario', models.CharField(max_length=20, null=True, verbose_name='Contraseña del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de reserva')),
                ('nombreUsuario', models.CharField(max_length=30, null=True, verbose_name='Nombre del usuario')),
                ('correoUsuario', models.EmailField(max_length=50, null=True, verbose_name='Correo del usuario')),
                ('nombreMascota', models.CharField(max_length=20, null=True, verbose_name='nombre de la mascota')),
                ('edadMascota', models.CharField(max_length=20, null=True, verbose_name='Edad de la mascota')),
                ('Archivos', models.ImageField(upload_to='Reserva', verbose_name='Archivos')),
                ('fechaReserva', models.DateField(auto_now=True, verbose_name='Fecha de la reservacion')),
                ('mensajeReserva', models.CharField(max_length=50, verbose_name='Mensaje de las reservaciones')),
                ('tipoReserva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.servicios', verbose_name='Tipo de reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigoChip', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo chip mascota')),
                ('MascotaNombre', models.CharField(max_length=50, null=True, verbose_name='Nombre de la mascota')),
                ('edadMascota', models.IntegerField(null=True, verbose_name='Edad de la mascota')),
                ('fechaNacimiento', models.DateField(auto_now=True, verbose_name='Fecha de nacimiento')),
                ('enfermedades', models.CharField(max_length=30, null=True, verbose_name='Enfermedad de la mascota')),
                ('foto', models.ImageField(upload_to='mascotas')),
                ('nombreDueno', models.CharField(max_length=50, null=True, verbose_name='Nombre del dueno')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.raza')),
            ],
        ),
    ]
