# Generated by Django 4.1.5 on 2023-05-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de la comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del detalle')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspecialidad', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de la especialidad')),
                ('nombreEspecialidad', models.CharField(max_length=35, null=True, verbose_name='Nombre de la especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('idMensaje', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del mensaje')),
                ('asuntoMensaje', models.CharField(max_length=10, null=True, verbose_name='Asunto del mensaje')),
                ('descripcionMensaje', models.CharField(max_length=10, null=True, verbose_name='Descripcion del mensaje')),
                ('fechaenvioMensaje', models.DateField(auto_now=True, verbose_name='Fecha de envio de los mensajes')),
                ('fechalecturaMensaje', models.DateField(auto_now=True, verbose_name='Fecha de la lectura de los mensajes')),
                ('statusMensaje', models.CharField(max_length=10, null=True, verbose_name='Status del mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('idPreguntas', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mensaje de consulta')),
                ('nombrePregunta', models.CharField(max_length=35, null=True, verbose_name='Nombre de la persona que hace las preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('codigoRaza', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la Raza')),
                ('nombreRaza', models.CharField(max_length=20, null=True, verbose_name='Nombre de la mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de la region')),
                ('nombreRegion', models.CharField(max_length=35, null=True, verbose_name='Nombre de la region')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo del rol de usuario')),
                ('nombreRol', models.CharField(max_length=45, null=True, verbose_name='Nombre del rol de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de los servicios')),
                ('nombreServicio', models.CharField(max_length=35, null=True, verbose_name='Nombre de los servicios')),
                ('precioServicio', models.IntegerField(null=True, verbose_name='El precio de los servicios ')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de usuario')),
                ('rutUsuario', models.CharField(max_length=10, null=True, verbose_name='Rut del usuario')),
                ('primerNombreUsuario', models.CharField(max_length=30, verbose_name='Nombre del usuario')),
                ('apellidoUsuario', models.CharField(max_length=30, verbose_name='Apellido del usuario')),
                ('correoUsuario', models.EmailField(max_length=45, verbose_name='Correo del usuario')),
                ('direccionUsuario', models.CharField(max_length=50, verbose_name='Direccion del usuario')),
                ('fechanacUsuario', models.DateField(auto_now=True, verbose_name='Fecha de nacimiento del usuario')),
                ('nombreUsuario', models.CharField(max_length=20, null=True, verbose_name='Nombre de inicio sesion del usuario')),
                ('claveUsuario', models.CharField(max_length=20, null=True, verbose_name='Conrtaseña del usuario')),
                ('respuestaUsuario', models.CharField(max_length=50, null=True, verbose_name='Respuesta al mensaje')),
                ('telefonoUsuario', models.IntegerField(null=True, verbose_name='Telefono del usuario')),
                ('idComuna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.comuna')),
                ('idEspecialidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.especialidad')),
                ('idPreguntas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.preguntas', verbose_name='Codigo de la pregunta')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('idRespuesta', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de la respuesta')),
                ('descripcionRespuesta', models.CharField(max_length=50, null=True, verbose_name='Descripcion de la respuesta de los mensajes')),
                ('statusRespuesta', models.CharField(max_length=10, null=True, verbose_name='Status de la respuesta de los mensajes')),
                ('idMensaje', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.mensaje')),
            ],
        ),
        migrations.AddField(
            model_name='mensaje',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.usuario'),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigoChip', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreMascota', models.CharField(max_length=50, verbose_name='Nombre de la mascota')),
                ('edadMascota', models.IntegerField(verbose_name='Edad de la mascota')),
                ('fechaNacimiento', models.DateField(auto_now=True, verbose_name='Fecha de nacimiento')),
                ('foto', models.ImageField(upload_to='mascotas')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.usuario')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.raza')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de la consulta')),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.mascota')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.region'),
        ),
    ]
