# Generated by Django 4.1.5 on 2023-05-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefonoUsuario',
            field=models.IntegerField(null=True, verbose_name='Telefono del usuario'),
        ),
    ]
